### ISSUE TITLE
Can't compile project on Xcode 15.2 & 14.3.2

### ISSUE THREAD

**Issue by bbjay** [dickygeraldi123/animal-discovery#5]
When trying to run your project I get the following error:
```
SDK does not contain 'libarclite' at the path 
'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a'; 
try increasing the minimum deployment target
```

What I've tried:
- raise minimum deployment target
- pod update
- pod deintegrate & pod install
- clean & build

Same result on Xcode 15.2 (macOS 14.2.1) & Xcode 14.3.2 (macOS 13.6.3)

**Comment by dickygeraldi123** [comment]
Hi, thanks for the comment. 

The error is because of the absence of '.a' files. You can clone this [project](https://github.com/kamyarelyasi/Libarclite-Files) and it works on my Xcode 15.0 (macOS 14.3).
